### PR TITLE
Use ke::AString to store strings from SP safely (Fixes #2)

### LINKED ISSUE #2: HTTP request failed using non-literal strings
I was trying to set up an HTTPClient using a string from a convar, but I ended up errors like:
```
HTTP request failed: Could not resolve host: http{weird character}
HTTP request failed: <url> malformed
```

I assumed the reason might be due to using a stack allocated string, instead of a string literal, so I've made a small test case which show cases both:
```sourcepawn
#include <sourcemod>
#include <ripext>

#define BASE_URL "http://echo.jsontest.com"

HTTPClient dynamicHttpClient;
HTTPClient literalHttpClient;

public void OnPluginStart()
{
    char baseUrl[32];
    strcopy(baseUrl, sizeof(baseUrl), BASE_URL);

    dynamicHttpClient = new HTTPClient(baseUrl);
    literalHttpClient = new HTTPClient(BASE_URL);

    dynamicHttpClient.Get("/immediate/get/dynamic/client", GetEcho);
    literalHttpClient.Get("/immediate/get/literal/client", GetEcho);

    CreateTimer(10.0, Tick);
}

public Action Tick(Handle timer, any data)
{
    dynamicHttpClient.Get("/delayed/get/dynamic/client", GetEcho);
    literalHttpClient.Get("/delayed/get/literal/client", GetEcho);
}

public void GetEcho(HTTPResponse response, any data)
{
    char json[128];
    response.Data.ToString(json, sizeof(json), JSON_INDENT(2));
    PrintToServer(json);
}
```
It outputs
```
{
  "dynamic": "client",
  "immediate": "get"
}
{
  "immediate": "get",
  "literal": "client"
}
L 07/27/2017 - 22:10:21: [RIPEXT] HTTP request failed: <url> malformed
{
  "delayed": "get",
  "literal": "client"
}
```
The client using the literal as baseurl works fine, but as soon as you change to something dynamically allocated, it doesn't work.

I'm guessing that baseUrl in [CreateClient ](https://github.com/ErikMinekus/sm-ripext/blob/a1da301c88af99f1e25cd3967301fabddb5c2100/curl_natives.cpp#L25) should be copied before being used to create HTTPClient, instead of being passed as-is.

For now, I'm working around it by creating a new HTTPClient for each request and deleting it in the callback, but if there's an error in the request, I can't delete the handle. At least without yet another work around, like a timer.

### PR DESCRIPTION
**Pull request by asherkin**
I _think_ this should be all the cases where SP-owned memory is being persisted internally, all the JSON natives looked fine. This could be fixed with a couple of `strdup`'s instead, but I think using AMTL is saner. `HTTPClient::BuildURL` is slightly unfortunate, appending to a `ke::AString` would be nice, but it is no worse than it was.

### CODE REVIEW

File: extension.h [hunk 1]
```diff
@@ -43,8 +43,8 @@ struct HTTPRequest {
 		}
 	}
 
-	const char *method;
-	const char *endpoint;
+	const ke::AString method;
+	const ke::AString endpoint;
 	json_t *data;
 
 	char *body;
```
Comment (asherkin) [inline extension.h]: Didn't do this one as `ke::AString` currently has no way to adopt a `char *` buffer, and it could be quite a large copy.
